apiVersion: v1
kind: Service
metadata:
  name: gorush
  labels:
    app: gorush
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: gorush
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8088
